num_epochs: 2
batch_size: 64
learning_rate: 0.001
optimizer: adam

img_size: 64
nb_conv_layers: 2
nb_layers: 2
net_width: 128
dropout_rates:
    - 0.3
    - 0.4

normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]