num_epochs: 2
batch_size: 64
learning_rate: 0.001
optimizer: adam

img_size: 64
nb_conv_layers: 2
nb_layers: 2
net_width: 128
dropout_rates:
    - 0.3
    - 0.4

normalization:
    mean: [0.5117, 0.5098, 0.5089]
    std: [0.2070, 0.2062, 0.2060]